### ISSUE TITLE
No permission though *

### ISSUE THREAD

**Issue by Konstanius** [NahuLD/AntiHostile#1]
Hello, I have just downloaded the plugin, put it in the server plugins folder and restarted the server, but if I do the command it tells me: "Sorry, but you dont have enough permissions for this command." (color is red)
I have the "*" permission and I am Operator on the server. This is weird

**Comment by NahuLD** [comment]
Issue should be solved, I will push the new compiled resource.

Everything should work fine now. Hopefully. Positively. Confidently. Surely.

**Comment by Konstanius** [comment]
Now the permission works, but the plugin does not do what its supposed to do. If I go in gamemode survival, do the command and get close to some mobs, they will attack me

**Comment by NahuLD** [comment]
I might have forgotten to register events. One second.

**Comment by Konstanius** [comment]
Still doesnt work. Did you do it for 1.12.2?

**Comment by NahuLD** [comment]
Alright I just debugged it and I know what you mean.
New mobs won't target you but mobs that were targetting you will not stop. Should be an easy fix.

**Comment by NahuLD** [comment]
Last release is tested to work. Enjoy.
